### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by maddycpierce** [acgd-webdev-3/animal-rescue-website#1]
Hi @thomasjbradley 
GitHub keeps giving me this whenever I try to commit something. I have tried signing out and back in to the account on the desktop version, but it didn't do anything to help. I have also tried deleting the repository and redownloading it, and that did nothing either.

What should I do?

Thanks, and Merry Christmas!
<img width="819" alt="screen shot 2017-12-26 at 10 34 59 am" src="https://user-images.githubusercontent.com/22149579/34359751-beb66452-ea28-11e7-81dc-b3ca3cdd343a.png">

**Comment by thomasjbradley** [comment]
It looks like the repo wasn't forked, or at least mine was cloned instead of yours being cloned.

We need to point the remote URL to a repository that you're authenticated on—AKA, your forked repo.

Go to the GitHub website, and copy the remote URL from your forked repo, then paste it into the remote URL in GitHub (`Repository > Repository Settings`).

![remote](https://user-images.githubusercontent.com/105192/34456706-6aee7468-ed6b-11e7-8635-4c9c465b8436.png)
